12 warnings generated.
/home/yannan/Honeynet/llvm-project/clang-tools-extra/test/clang-tidy/bsl-temp.cpp:4:5: warning: Identifier typographically ambiguous with identifier 'id1_a_b_c' on line 3 [bsl-identifier-typographically-unambiguous]
int id1_abc; // Non-compliant
    ^
/home/yannan/Honeynet/llvm-project/clang-tools-extra/test/clang-tidy/bsl-temp.cpp:8:5: warning: Identifier typographically ambiguous with identifier 'id2_abc' on line 7 [bsl-identifier-typographically-unambiguous]
int id2_ABC; // Non-compliant
    ^
/home/yannan/Honeynet/llvm-project/clang-tools-extra/test/clang-tidy/bsl-temp.cpp:12:5: warning: Identifier typographically ambiguous with identifier 'id3_a_bc' on line 11 [bsl-identifier-typographically-unambiguous]
int id3_ab_c; // Non-compliant
    ^
/home/yannan/Honeynet/llvm-project/clang-tools-extra/test/clang-tidy/bsl-temp.cpp:16:5: warning: Identifier typographically ambiguous with identifier 'id4_a_bc' on line 15 [bsl-identifier-typographically-unambiguous]
int id4_ab_c; // Non-compliant
    ^
/home/yannan/Honeynet/llvm-project/clang-tools-extra/test/clang-tidy/bsl-temp.cpp:20:5: warning: Identifier typographically ambiguous with identifier 'id5_ii' on line 19 [bsl-identifier-typographically-unambiguous]
int id5_11; // Non-compliant
    ^
/home/yannan/Honeynet/llvm-project/clang-tools-extra/test/clang-tidy/bsl-temp.cpp:24:5: warning: Identifier typographically ambiguous with identifier 'id6_i0' on line 23 [bsl-identifier-typographically-unambiguous]
int id6_1O; // Non-compliant
    ^
/home/yannan/Honeynet/llvm-project/clang-tools-extra/test/clang-tidy/bsl-temp.cpp:28:5: warning: Identifier typographically ambiguous with identifier 'id7_in' on line 27 [bsl-identifier-typographically-unambiguous]
int id7_1h; // Non-compliant
    ^
/home/yannan/Honeynet/llvm-project/clang-tools-extra/test/clang-tidy/bsl-temp.cpp:32:5: warning: Identifier typographically ambiguous with identifier 'id8_Z5' on line 31 [bsl-identifier-typographically-unambiguous]
int id8_2S; // Non-compliant
    ^
/home/yannan/Honeynet/llvm-project/clang-tools-extra/test/clang-tidy/bsl-temp.cpp:36:5: warning: Identifier typographically ambiguous with identifier 'id9_ZS' on line 35 [bsl-identifier-typographically-unambiguous]
int id9_25; // Non-compliant
    ^
/home/yannan/Honeynet/llvm-project/clang-tools-extra/test/clang-tidy/bsl-temp.cpp:41:6: warning: Identifier typographically ambiguous with identifier 'frn0' on line 40 [bsl-identifier-typographically-unambiguous]
void frno();
     ^
/home/yannan/Honeynet/llvm-project/clang-tools-extra/test/clang-tidy/bsl-temp.cpp:45:6: warning: Identifier typographically ambiguous with identifier 'frn' on line 44 [bsl-identifier-typographically-unambiguous]
void fm();
     ^
/home/yannan/Honeynet/llvm-project/clang-tools-extra/test/clang-tidy/bsl-temp.cpp:47:6: warning: Identifier typographically ambiguous with identifier 'frn' on line 44 [bsl-identifier-typographically-unambiguous]
void f___m();
     ^
